name: Deploy
on:
  pull_request:
  push:
    branches-ignore:
      - 'master'
      - 'prod'


concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  testEnv: ${{ vars.TEST_ENV }}

jobs:
  style_checks:
    name: Code Styling check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - run: "echo checking code style"