name: Deploy Production

on:
  push:
    branches:
      - master
  
jobs:
  deploy:
    uses: leanazulyoro/test_gh_actions/.github/workflows/reusable-deploy.yml@develop
    with:
      environment: production


      