name: Deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env: 
  testEnv: ${{ vars.TEST_ENV }}
  
jobs:
  deploy:
    name: Deploy
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest 
    
    steps: 
      - uses: actions/checkout@v2
      - name: Notify deployment started
        uses: ./.github/actions/notify-deployment-started
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          app_name: Test GH Actions
          staging_slack_channel: D02MM7KJP0A
          staging_branch: 'develop'
          prod_branch: 'main'
          prod_slack_channel: D02MM7KJP0A
          prod_slack_mention: <@D02MM7KJP0A>
          
      - run: "echo Deploy to ${{ inputs.environment }} using var TEST_ENV: ${{ vars.TEST_ENV }}"
  


      