name: Deploy Staging

on:
  push:
    branches:
      - develop
  
jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
    secrets:
      MY_REPO_SECRET: ${{ secrets.MY_REPO_SECRET }}


      