name: Deploy

on:
  push:
    branches:
      - develop
  
jobs:
  deploy:
    uses: leanazulyoro/test_gh_actions/.github/workflows/reusable-deploy.yml@master
    with:
      environment: staging


      