name: Deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  testEnv: ${{ vars.TEST_ENV }}
  
jobs:
  deploy:
    name: Deploy
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest 
    
    steps:
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with: 
          time: '30s'
      - run: "echo Deploy to ${{ inputs.environment }} using var TEST_ENV: ${{ vars.TEST_ENV }}"
  


      