name: Deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

concurrency: ci-${{ github.ref }}

env:
  testEnv: ${{ vars.TEST_ENV }}
  
jobs:
  deploy:
    name: Deploy
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - run: "echo Deploy to ${{ inputs.environment }} using var TEST_ENV: ${{ vars.TEST_ENV }}"
  


      