on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "channel": "@leandro",
              "username": "Github Actions Deployment Monitor",
              "text": "<@leandro> A deploy to Metronome app in staging has just finished (MENTIRA, ES UNA PRUEBA) ${{ env.GITHUB_BASE_REF }}",
              "icon_emoji": ":github:"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}