on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    runs-on: ubuntu-latest
    steps:
        
      # @here A deploy to Bloq Services in staging is starting - [Merge pull request #1144 from bloqpriv/flag_update](Merge commit message)
      # [Flag updated for node connection example](PR title).
        
        
        
        
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "channel": "@leandro",
              "username": "Github Actions Deployment Monitor",
              "text": "<@leandro> job.status: ${{ job.status }} / head_commit.message ${{ github.event.head_commit.message }}",
              "icon_emoji": ":github:"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}