on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Notify deployment started
        uses: ./.github/actions/notify-deployment-started

      - name: Notify deployment finished
        uses: ./.github/actions/notify-deployment-finished