on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    runs-on: ubuntu-latest
    steps:
        
      # @here A deploy to Bloq Services in staging is starting - [Merge pull request #1144 from bloqpriv/flag_update](Merge commit message)
      # [Flag updated for node connection example](PR title).


      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        if: ${{ github.ref_name == 'develop' }}
        with:
          payload: |
            {
              "channel": "@leandro",
              "username": "Github Actions Deployment Monitor",
              "text": "<@leandro> A deploy to Metronome app in staging is starting - ${{ github.event.head_commit.message }}",
              "icon_emoji": ":github:"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        if: ${{ github.ref_name == 'develop' }}
        with:
         payload: |
           {
             "channel": "@leandro",
             "username": "Github Actions Deployment Monitor",
             "text": "<@leandro> A deploy to Metronome app in staging has just finished.",
             "icon_emoji": ":github:"
           }
        env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}


      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        if: ${{ github.ref_name == 'main' }}
        with:
          payload: |
            {
              "channel": "@leandro",
              "username": "Github Actions Deployment Monitor",
              "text": "<@leandro> A deploy to Metronome app in prod is starting - ${{ github.event.head_commit.message }}",
              "icon_emoji": ":github:"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          
      - name: Send custom JSON data to Slack workflow
          id: slack
          uses: slackapi/slack-github-action@v1.23.0
          if: ${{ github.ref_name == 'main' }}
          with:
            payload: |
              {
                "channel": "@leandro",
                "username": "Github Actions Deployment Monitor",
                "text": "<@leandro> A deploy to Metronome app in prod has just finished.",
                "icon_emoji": ":github:"
              }
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}